branches:
  only:
  - master

language: php

sudo: false

php:
  - 7.1
  - 7.2

before_install:
  - nvm install node
  - nvm alias default node
  - node --version

before_script:
  - mysql -uroot -e "create database gotea_test"
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - sh -c "cp .env.example .env"
  - phpenv rehash
  - npm install

script:
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests"
  - sh -c "vendor/bin/phpunit --colors"
  - sh -c "npm run lint"

notifications:
  email: false
