branches:
  only:
  - master

language: php

sudo: false

php:
  - 7.1

before_install:
  - nvm install node
  - nvm alias default node
  - node --version

before_script:
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - phpenv rehash
  - npm install

script:
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./webroot"
  - sh -c "npm run lint"

notifications:
  email: false
