version: '3'
services:
  backend:
    image: ghcr.io/gotoeveryone/composer-php:7.4
    volumes:
      - ./:/src
      - vendor:/src/vendor
    ports:
      - '8765:8765'
    depends_on:
      - database
    working_dir: /src
    command: sh -c 'composer install -n && ./bin/cake server --host 0.0.0.0'
    tty: true
  frontend:
    image: node:14.16
    volumes:
      - ./:/src
      - node_modules:/src/node_modules
    working_dir: /src
    command: sh -c 'npm i && npm run dev'
    tty: true
  database:
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
      - ./tests/setup.sh:/docker-entrypoint-initdb.d/setup.sh
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'gotea'
      MYSQL_TEST_DATABASE: 'gotea_test'
      TZ: 'Asia/Tokyo'
    ports:
      - '33306:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

volumes:
  node_modules:
  vendor:
