version: '3'
services:
  server:
    container_name: app
    build: ./docker/app
    volumes:
      - ./:/src
    ports:
      - '8765:8765'
    depends_on:
      - database
    working_dir: /src
    command: sh -c 'composer install -n && ./bin/cake server --host 0.0.0.0'
  resources:
    image: node:12
    container_name: resources
    volumes:
      - ./:/src
    working_dir: /src
    command: sh -c 'yarn && yarn dev'
  database:
    container_name: database
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
      - ./tests/setup.sh:/docker-entrypoint-initdb.d/setup.sh
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'gotea'
      MYSQL_TEST_DATABASE: 'gotea_test'
      TZ: 'Asia/Tokyo'
    ports:
      - '53306:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
