#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: stylish
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: 'resources/assets/sass/**/*.s+(a|c)ss'
  ignore:
    - 'sass/vendor/**/*.*'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 4
  property-sort-order:
    - 1
    -
      order:
        - display
        - position
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left
        - padding
      ignore-custom-properties: true
  zero-unit:
    - 1
