FROM php:7-fpm
MAINTAINER Kazuki_Kamizuru<kamizuru@k2ss.info>

RUN apt-get update \
    && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng12-dev libmcrypt-dev zlib1g-dev libicu-dev g++ \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl pdo_mysql mysqli mbstring gd iconv mcrypt \
    && apt-get clean
