name: Ansible

on:
  push:
    paths:
      - infra/**

jobs:
  ansible_lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
          cache-dependency-glob: infra/uv.lock
      - name: Install Dependencies
        run: uv sync --locked
      - name: Execute Lint
        run: uv run --locked ansible-lint ./
