name: Ansible

on:
  push:
    paths:
      - infra/**

jobs:
  ansible_lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: "3.12"
          cache: pipenv
          cache-dependency-path: |
            infra/Pipfile.lock
      - name: Setup Pipenv
        run: pip install pipenv
      - name: Install Dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: pipenv install -d
      - name: Execute Lint
        run: pipenv run lint
